### ISSUE TITLE
Type definition of getProxySettings() is not accurate

### ISSUE THREAD

**Issue by Maxim-Mazurok** [Azure/get-proxy-settings#24]
As you can see in [dist/proxy.d.ts](https://unpkg.com/get-proxy-settings@0.1.11/dist/proxy.d.ts):
```ts
export declare function getProxySettings(): Promise<ProxySettings>;
```
`getProxySettings()` always returns promise that resolves to `ProxySettings`.

While in reality, it may return `null`:
https://github.com/Azure/get-proxy-settings/blob/84f90a39011cbd291d54385af0b77493c7173b26/src/proxy.ts#L9

As you can see, my code:
```ts
const proxy = await getProxySettings();
const bestProxy = proxy.https || proxy.http || undefined;
```
compiled without any warning, but failed with error:
```
TypeError: Cannot read property 'https' of null
    at /home/runner/work/google-api-typings-generator/google-api-typings-generator/src/cli.ts:31:27
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
```
while [running](https://github.com/Maxim-Mazurok/google-api-typings-generator/pull/191/checks?check_run_id=696307628#step:7:9)

So, the correct type definition should be:
```ts
export declare function getProxySettings(): Promise<ProxySettings | null>;
```

**Comment by Maxim-Mazurok** [comment]
@timotheeguerin is this project maintained?

**Comment by timotheeguerin** [comment]
Version 0.1.12 should have that fixed. Seems like the typing was fixed a while back but never published a new version

**Comment by Maxim-Mazurok** [comment]
Thank you so much! It worked beautifully: https://github.com/Maxim-Mazurok/google-api-typings-generator/pull/312
